### ISSUE TITLE
Dashboard options/settings plugin page visible to custom role

### ISSUE THREAD

**Issue by steveadamsfixedit** [ColoredCow/wp-plugin-boilerplate#16]
I'm building a plugin based on the boilerplate that contains analytics data on virtual events attended by logged in users. The entire system is restricted to a hierarchy of users from the top down as follows: Admins, Moderators, Presenters, Attendees. I've granted Moderators access to the WP dashboard where I want to display a 'settings/options' page where they can see the activity analytics data of the attendees for only the events that are under their moderation control. Admins should be able to see all event analytics for all events tied to all moderators. 
   Currently, I've constructed this page in my custom_plugin/admin/partials/custom_plugin-events.php file and it is displaying all the activity at an administrator level. Furthermore, I've constructed the custom post type for the events and the custom roles with access. The moderator can see the custom post type in their dashboard.
    My question is threefold:

1) How do I make the event analytics page at the wp-admin/admin.php?page=custom_plugin-events url visible in the moderator's dashboard?
2) I'm presently using some conditional logic in this admin/partial page that basically says if user_can=admin show this data and if user_can=moderator show this other data. Is that the correct and recommended approach? 
3) If I'm requiring all these users to be logged in and applied to one custom role or another...is the custom_plugin/admin directory  the correct place to implement this? or would it be better in custom_plugin/public?

**Comment by pokhiii** [comment]
@steveadamsfixedit This boilerplate is based on the structure of WooCommerce. So, I'll try to answer you queries taking example from WooCommerce:

1. WC has a **Reports** page accessible at `wp-admin/admin.php?page=wc-reports`. The code for this is written in `woocommerce/includes/admin/class-wc-admin-menus.php`.
See for reference: https://github.com/woocommerce/woocommerce/blob/4668ca5f6ff62f7f79833858909ec0f3835a346b/plugins/woocommerce/includes/admin/class-wc-admin-menus.php#L69-L78

2. That is fine. However, the recommended approach would be to use a capability instead of roles: like `current_user_can( 'view_analytics_data' )`

3. `custom_plugin/admin` is not something in our plugin. `custom_plugin/includes/admin` is a directory provided by this boilerplate. The directory code is loaded on all the admin requests (`is_admin() === true`). See this check https://github.com/ColoredCow/wp-plugin-boilerplate/blob/96f6318a64a8f28711326aac1aaab5569bc0e660/includes/class-wp-plugin-boilerplate.php#L213-L215

Also, it seems from the description you've provided that you are using some other boilerplate instead of this one (`custom_plugin/admin/partials/custom_plugin-events.php` this boilerplate does NOT give a `partials` directory). Therefore, it'd be more helpful for you to ask this in the appropriate boilerplate repository. I'd be closing this issue for the same but if you think this is a mistake feel free to respond or open a new issue.

Thanks
